name: Dockerized App Deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 24700
          script: |
            cd /root/instagraaa/instagrambackend
            git fetch origin 
            git checkout master
            git pull origin master
            docker build -t instagrambackend .
            docker stop instagrambackend-container || true
            docker rm instagrambackend-container || true
            docker run -d --name instagrambackend-container -p 4002:8081 instagrambackend
            docker ps -a
            docker images
